### ISSUE TITLE
[🐧 v 🗗 v 🍎] Don't use `open` for opening the result

### ISSUE THREAD

**Issue by mariobodemann** [savvasdalkitsis/module-dependency-graph#1]
Hey,

I just used the plugin for the first time, and the results look nice. Thanks for that.

Sadly, I found that the build on my local machine (Linux), due to `open` not being a command to be used like on Mac. (see https://github.com/savvasdalkitsis/module-dependency-graph/blob/master/src/main/groovy/com/savvasdalkitsis/module/deps/graph/ModuleDependencyGraphPlugin.groovy#L51-L54) This might also be an issue on Windows, tbh.

Maybe we can just output the path of the result?

**Comment by asos-savvasdalkitsis** [comment]
Hey Mario! Thanks for the feedback :)

My intention is to make this plugin platform agnostic and very customisable (wether you want to open the image will be a parameter etc).

I only published this VERY early draft cause i wanted to test the gradle plugin deployment pipeline.

I will make sure to introduce an 'open' parameter very soon to unblock you at least.

Btw, I'm surprised this didn't work for you. `open` should be a standard command on Linux as well. Which distro are you using out of curiosity?

**Comment by savvasdalkitsis** [comment]
Hey Mario! Thanks for the feedback :)

My intention is to make this plugin platform agnostic and very customisable (wether you want to open the image will be a parameter etc).

I only published this VERY early draft cause i wanted to test the gradle plugin deployment pipeline.

I will make sure to introduce an 'open' parameter very soon to unblock you at least.

Btw, I'm surprised this didn't work for you. open should be a standard command on Linux as well. Which distro are you using out of curiosity?

**Comment by savvasdalkitsis** [comment]
Turns out I was wrong and open is not a Linux command. My bad. I will release an updated version soon

**Comment by savvasdalkitsis** [comment]
Sorry for the VERY late update on this. Can you try version 0.6 and let me know if it works?

**Comment by mariobodemann** [comment]
With `0.6` it works like a charm, thanks.
