### ISSUE TITLE
Configuration with name 'implementation' not found.

### ISSUE THREAD

**Issue by blundell** [savvasdalkitsis/module-dependency-graph#2]
Hey Savvas :-) small world

Looks like our build might have a quirky setup.

After calling: 
`$ sudo apt-get install graphviz`
`$ ./gradlew graphModules`

![image](https://user-images.githubusercontent.com/655860/74524335-c0c17480-4f16-11ea-8ec6-e1c9c505615a.png)

anything you want to know to debug?

**Comment by savvasdalkitsis** [comment]
Hey Paul. Small world indeed :)

Someone else raised this too on slack. I will try to replicate and fix it. If I can't, I might ask for a skeleton project that exhibits the issue to troubleshoot

**Comment by blundell** [comment]
Hope you're doing good.

The only thing I can think of is its something to do with multi-module projects.

From the web:
> The implementation configuration is registered by the java plugin

**Comment by markuskallander** [comment]
@blundell Did you manage to fix this issue? I have the same problem in a multi module project.

**Comment by blundell** [comment]
@markuskallander no I didn't sorry :-(

**Comment by savvasdalkitsis** [comment]
Apologies folks. I had a crazy half year so I neglected this project. I will get on this.

**Comment by savvasdalkitsis** [comment]
Sorry for the VERY late update on this. Can you try version 0.6 and let me know if it works?

**Comment by blundell** [comment]
yep, all good - tried version 0.9 and it's generating the graph now :100:
