### ISSUE TITLE
What's the difference between this and jake whartons dependency task?

### ISSUE THREAD

**Issue by ColtonIdle** [savvasdalkitsis/module-dependency-graph#4]
I learned about jakes dep task in a few blog posts but most recently here from Chris Banes. https://medium.com/androiddevelopers/jetpack-compose-before-and-after-8b43ba0b7d4f

He links out to:
https://github.com/JakeWharton/SdkSearch/blob/master/gradle/projectDependencyGraph.gradle

Is any one of these better than the other?

**Comment by savvasdalkitsis** [comment]
Huh, I wasn't aware Jake wrote one too. His seems to predate mine too. I haven't tried to compare but from the looks of it it handles multiplatform projects with different colours too.

Mine has some options to configure the output that Jake's is missing though. It's also packaged as a gradle plugin for easier integration with projects.

**Comment by ColtonIdle** [comment]
I did find his script to be a bit more readable on the same project, but I guess that's just a graphviz thing. anyway Thanks for answering!
